language: ruby
cache: bundler
sudo: false
addons:
  postgresql: "9.4"
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - cp config/secrets.yml.example config/secrets.yml
  - bundle exec rake db:test:prepare
script:
  - bundle exec rake db:schema:load
  - bundle exec rake db:test:prepare
  - bundle exec rspec
rvm:
  - 2.2.0
branches:
  only:
    - develop
